### ISSUE TITLE
Add pkgdown custom CSS as a function?

### ISSUE THREAD

**Issue by sebble** [jumpingrivers/inteRgrate#24]
See https://gitlab.com/jr-cloud/training/welcome-page/-/blob/master/.gitlab-ci.yml#L45

Create file `pkgdown/extra.css` before running `pkgdown::build_site()`

Suggested contents:

```css
.template-news h1 em {
    color: #999;
    font-size: .8em;
    font-style: normal;
}
.template-news h1 em::before {
    content: " - ";
}
```

Perhaps add to `/inst` for easy copying?
